### ISSUE TITLE
Hogy kell telepíteni?

### ISSUE THREAD

**Issue by meszaros-lajos-gyorgy** [OrsosAdam/roka-olvaso#1]

**Comment by OrsosAdam** [comment]
Kedves Lajos György!

Köszönöm az issue-t! 

Természetesen el fog készülni a leírás minél hamarabb. 

Javaslom, hogy kövesse a repositoryt, hogy mindig naprakész legyen az újításokkal!

Szívélyes üdvözlettel,
Ádám

**Comment by OrsosAdam** [comment]
@meszaros-lajos-gyorgy , Kérem, ha nem megfelelőnek találja a leírást, jelezze. 

Köszönöm!
